services:
  postgres:
    image: postgres:16-alpine
    container_name: modapk_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: modapk_store
      POSTGRES_USER: modapk_admin
      POSTGRES_PASSWORD: modapk_secret_2024
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
